<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/02/11 11:10:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => '3afritto',
  'name' => 'doctrine',
)),);
